### ISSUE TITLE
Crash when creating more than one new window on macOS

### ISSUE THREAD

**Issue by jeep70** [jeep70/qView#141]

**Comment by gbIxaHue** [comment]
Cant open more than one window on macOS

Process:               qView [828]
Path:                  /Applications/qView.app/Contents/MacOS/qView
Identifier:            com.qview.qView
Version:               2.0 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           qView [828]
User ID:               501

Date/Time:             2019-12-16 17:38:48.145 +0300
OS Version:            Mac OS X 10.14.5 (18F203)
Report Version:        12
Bridge OS Version:     3.5 (16P5200)
Anonymous UUID:        431471DA-8B77-71A9-3B4E-E61EEEF0E06B


Time Awake Since Boot: 6100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [828]

VM Regions Near 0x18:
--> 
    __TEXT                 000000010879d000-000000010880f000 [  456K] r-x/rwx SM=COW  /Applications/qView.app/Contents/MacOS/qView

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.qview.qView               	0x00000001087c09a0 QVImageCore::loadFile(QString const&) + 768
1   com.qview.qView               	0x00000001087a9b79 MainWindow::openFile(QString const&) + 297
2   com.qview.qView               	0x00000001087b995f QVApplication::event(QEvent*) + 79
3   org.qt-project.QtWidgets      	0x00000001088936fd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
4   org.qt-project.QtWidgets      	0x0000000108894b02 QApplication::notify(QObject*, QEvent*) + 594
5   org.qt-project.QtCore         	0x00000001096a9e44 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
6   org.qt-project.QtGui          	0x0000000108e56a02 QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 610
7   org.qt-project.QtGui          	0x0000000108e3e2c1 QWindowSystemInterface::handleFileOpenEvent(QString const&) + 65
8   libqcocoa.dylib               	0x000000010b7d66f0 0x10b7a0000 + 222960
9   com.apple.AppKit              	0x00007fff305074bc withWindowOrderingObserverHeuristic + 455
10  com.apple.AppKit              	0x00007fff30507188 -[NSApplication(NSAppleEventHandling) _openURLs:withCompletionHandler:] + 998
11  com.apple.AppKit              	0x00007fff3036ef3e __69-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]_block_invoke + 886
12  com.apple.AppKit              	0x00007fff3036eb3d -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] + 228
13  com.apple.AppKit              	0x00007fff3003b8eb -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 764
14  com.apple.Foundation          	0x00007fff34c54bec -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 286
15  com.apple.Foundation          	0x00007fff34c54a69 _NSAppleEventManagerGenericHandler + 102
16  com.apple.AE                  	0x00007fff33bd6397 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1815
17  com.apple.AE                  	0x00007fff33bd5c29 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41
18  com.apple.AE                  	0x00007fff33bd5b01 aeProcessAppleEvent + 414
19  com.apple.HIToolbox           	0x00007fff31ca6e97 AEProcessAppleEvent + 54
20  com.apple.AppKit              	0x00007fff30037c7e _DPSNextEvent + 1724
21  com.apple.AppKit              	0x00007fff3003671f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
22  com.apple.AppKit              	0x00007fff3003083c -[NSApplication run] + 699
23  libqcocoa.dylib               	0x000000010b7d3ccb 0x10b7a0000 + 212171
24  org.qt-project.QtCore         	0x00000001096a550f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
25  org.qt-project.QtCore         	0x00000001096aa452 QCoreApplication::exec() + 130
26  com.qview.qView               	0x00000001087a0fb8 main + 984
27  libdyld.dylib                 	0x00007fff5e8e03d5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff5ead33f0 start_wqthread + 0

Thread 8:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff5ea1886a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5ead756e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x00000001094ebb9f 0x1094c1000 + 175007
3   org.qt-project.QtCore         	0x00000001094eb88e 0x1094c1000 + 174222
4   org.qt-project.QtCore         	0x00000001094eb7cc QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
5   org.qt-project.QtCore         	0x00000001094eb72e QWaitCondition::wait(QMutex*, unsigned long) + 62
6   org.qt-project.QtCore         	0x00000001094e81f7 0x1094c1000 + 160247
7   org.qt-project.QtCore         	0x00000001094e3073 0x1094c1000 + 139379
8   libsystem_pthread.dylib       	0x00007fff5ead42eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff5ead7249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff5ead340d thread_start + 13

Thread 9:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff5ea1886a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5ead756e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x00000001094ebb9f 0x1094c1000 + 175007
3   org.qt-project.QtCore         	0x00000001094eb88e 0x1094c1000 + 174222
4   org.qt-project.QtCore         	0x00000001094eb7cc QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
5   org.qt-project.QtCore         	0x00000001094eb72e QWaitCondition::wait(QMutex*, unsigned long) + 62
6   org.qt-project.QtCore         	0x00000001094e81f7 0x1094c1000 + 160247
7   org.qt-project.QtCore         	0x00000001094e3073 0x1094c1000 + 139379
8   libsystem_pthread.dylib       	0x00007fff5ead42eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff5ead7249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff5ead340d thread_start + 13

Thread 10:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff5ea1886a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5ead756e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x00000001094ebb9f 0x1094c1000 + 175007
3   org.qt-project.QtCore         	0x00000001094eb88e 0x1094c1000 + 174222
4   org.qt-project.QtCore         	0x00000001094eb7cc QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
5   org.qt-project.QtCore         	0x00000001094eb72e QWaitCondition::wait(QMutex*, unsigned long) + 62
6   org.qt-project.QtCore         	0x00000001094e81f7 0x1094c1000 + 160247
7   org.qt-project.QtCore         	0x00000001094e3073 0x1094c1000 + 139379
8   libsystem_pthread.dylib       	0x00007fff5ead42eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff5ead7249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff5ead340d thread_start + 13

Thread 11:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff5ea1886a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5ead756e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x00000001094ebb9f 0x1094c1000 + 175007
3   org.qt-project.QtCore         	0x00000001094eb88e 0x1094c1000 + 174222
4   org.qt-project.QtCore         	0x00000001094eb7cc QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
5   org.qt-project.QtCore         	0x00000001094eb72e QWaitCondition::wait(QMutex*, unsigned long) + 62
6   org.qt-project.QtCore         	0x00000001094e81f7 0x1094c1000 + 160247
7   org.qt-project.QtCore         	0x00000001094e3073 0x1094c1000 + 139379
8   libsystem_pthread.dylib       	0x00007fff5ead42eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff5ead7249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff5ead340d thread_start + 13

Thread 12:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5ea1522a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5ea1576c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff329b2bee __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff329b215c __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff329b18be CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff3003f6a6 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5ead42eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5ead7249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5ead340d thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000060000194c9d8  rbx: 0x00007f8870d28820  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000109a00cf0  rsi: 0x0000000000000000  rbp: 0x00007ffee7461230  rsp: 0x00007ffee74611a0
   r8: 0x0000e4ded41cc9c0   r9: 0x0000000000000002  r10: 0x00007ffee7462d00  r11: 0x0000000108ed0bd0
  r12: 0x00007ffee74612a8  r13: 0x00007f8870d28828  r14: 0x00007f8870d28890  r15: 0x00007f8870d287d8
  rip: 0x00000001087c09a0  rfl: 0x0000000000010297  cr2: 0x0000000000000018
  
Logical CPU:     2
Error Code:      0x00000006
Trap Number:     14

**Comment by jurplel** [comment]
This is already fixed, I will release a new version in the next week or so.
